# Generated by Django 5.2.7 on 2025-10-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquapark', '0002_remove_employee_password_customuser_employee_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('cashier', 'Кассир'), ('admin', 'Администратор')], default='cashier', max_length=10, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cashier', 'Кассир'), ('admin', 'Администратор')], default='cashier', max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('cashier', 'Кассир'), ('admin', 'Администратор')], max_length=10, verbose_name='Должность'),
        ),
    ]
