# Generated by Django 5.2.7 on 2025-10-16 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquapark', '0003_customuser_position_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('user', 'Пользователь'), ('cashier', 'Кассир'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('cashier', 'Кассир'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('user', 'Пользователь'), ('cashier', 'Кассир'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зарплата'),
        ),
    ]
